Feature/6 admin dashboard layout
sosaidi/AdvancedMD-frontend pull request #29
Opened 2024-12-27 18:00 UTC by n1munjulur

This is the basic Admin dashboard layout implementation [Not yet integrated with the backend]. The Admin dashboard has components like Staff, Patients, Payments, and Rooms. The styling of each component is also updated

2024-12-27 19:34 UTC, sosaidi approved these changes
The design can be adjusted at a later stage, as it will need to align with the other dashboards for consistency. The "doctors" route currently doesn't lead anywhere (not sure if it's redundant or just incomplete). Additionally, the design still needs to be reimplemented using Tailwind CSS, as we agreed on that approach. The functionality can be addressed in a future issue. I'll approve the review since it serves as a basic structural foundation for now.

2024-12-27 21:09 UTC, n1munjulur commented
Yes, thanks! The basic structure is implemented so far and yes I will update the design using Tailwind later.
Also, the doctor route doesn't navigate further, I will have to check on this too.

2024-12-29 19:20 UTC, clermona commented
The Authentication service will not work at this point with backend. The Mocked Objects will not come with the properties  and with the specified types, please have a look at the sql file we shared in our group chat.

2024-12-29 19:45 UTC, clermona requested changes
Please also edit your file structure so that it matches with the code structure in the current main branch. And remove the code in the app routes as this will already be overwritten in each component (have a look in the main branch).

2024-12-29 19:54 UTC, sosaidi requested changes
as @clermona mentionent

2025-01-07 09:25 UTC, closed without merging